### ISSUE TITLE
TODO:  11/15/2020

### ISSUE THREAD

**Issue by nbora0911** [nbora0911/tabot#3]
- [ ] -[] Download SQUAD dataset
- [ ] -[] Define input structure
- [ ] -[] Define output structure
- [ ] -[] Define loss and evaluation metric
- [ ] -[] Quick and dirty model
- [ ] Gather data for tabot
- [ ] [Read/listen to lecture + read suggested material ](http://web.stanford.edu/class/cs224n/)
